# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.gruasyplataformas.mx
title: Grúas y Plataformas
email: amecomx@gmail.com 
author: Juan Manuel Andrade Ruiz
description: "Asesoría profesional de equipo pesado especializado en grúas y plataformas de las marcas Manitowoc JLG Grove Palfinger National. Estamos a tu servicio como representate oficial AMECO. Venta de equipo nuevo para la construcción"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/pages/Gr%C3%BAas-y-Plataformas/881963701841537
  - title: twitter
    url: https://twitter.com/saleyvale
  - title: linkedin
    url: https://mx.linkedin.com/in/gruasyplataformas

# ----------------------- #
#     Color Settings      #
# ----------------------- #
color:
  primary: 18bc9c
  primary-rgb: "24,288,156"

gems:
  - jekyll-sitemap
